
version: '2'
services:
  web:
    image: ditsara/jekyll-test:development
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: "bundle exec jekyll serve --watch --incremental"
